# Generated by Django 4.2.16 on 2024-10-30 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 10, 30, 19, 45, 56, 119709)
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
            },
        ),
    ]
