# Generated by Django 4.2.16 on 2024-10-30 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
